### PR TITLE
updated council URL

### PR DESCRIPTION
**Pull request by LoveMyData**
adjusted code to suit new web site's format
updated README.md

### CODE REVIEW

**Comment by henare** [comment]
@LoveMyData it would be great if you include a link to your scraper on morph.io so we can quickly check all looks good: https://morph.io/LoveMyData/shellharbour

I've noticed some missing addresses in your data. Can you see if you can fix this?

**Comment by henare** [comment]
@LoveMyData wrote in Slack:

> where do you see the blank record? it is under by repo, I think it was a bug fixed in previous commit.

The first address record on your morph.io scraper is currently blank for example. Council reference "684/2015".

**Comment by LoveMyData** [comment]
Those records were old and from previous commits, only way to fix it is delete the data.sqllite or access the backend and remove those entries via SQL command.

**Comment by henare** [comment]
No problem. Can you clear your database and rerun it so I can see a clean run?

**Comment by LoveMyData** [comment]
DB cleared

**Comment by henare** [comment]
LGTM :+1:

**Pull request merged**
